default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.6.0
    hooks:
      - id: autoflake
        name: Autoflake
        exclude: (deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|LNLS|MAXIV|SOLEIL|ANSTO))
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-duplicate-keys
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    - id: black
      name: Black
      language_version: python3.7
      exclude: (deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|LNLS|MAXIV|SOLEIL|ANSTO))
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: (deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|LNLS|MAXIV|SOLEIL|ANSTO))
      - id: check-case-conflict
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        exclude: ^.drone\.yml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Import Sort
        args:
          - --settings=.
        exclude: (/__init__\.py$|deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|LNLS|MAXIV|SOLEIL|ANSTO))
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      name: Flake8
      additional_dependencies: ["flake8-bugbear==22.9.11"]
      exclude: (deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|LNLS|MAXIV|SOLEIL|ANSTO))
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
