---

# The class to initialise, and init parameters
class: mxcubecore.HardwareObjects.Beamline.Beamline
# Further key-value pairs here will be passed to the class init
# mode: devel

# objects
#
# Eventually all objects should use the yaml config system like Beamline,
# but for now we can leave them as xml
#
# NBNB some objects that do not currently have their own config files
# would need those added (e.g. the centring methods)
#
objects:
  # The !!o0map and the lines starting with '- ' give you an *ordered* dictionary
  # And thus a reproducible loading order
  !!omap
  # The values are the file paths to the configuration file for the
  # object, relative to the configuration file path(s)
  #
  # NB - the order is *NOT* arbitrary, as signal connnections are set
  # on one object that require the other to be already loaded.
  #
  # Hardware:
  - session: session.xml
  - machine_info: mach-info-mockup.xml
  - transmission: transmission-mockup.xml
  - energy: energy-mockup.xml
  - beam: beam-mockup.xml
  - flux: flux-mockup.xml
  - detector: detector-mockup.xml
  - resolution: resolution-mockup.xml
  - hutch_interlock: door-interlock-mockup.xml
  - safety_shutter: safety-shutter-mockup.xml
  - fast_shutter: fast-shutter-mockup.xml
  - sample_changer: sample-changer-mockup.xml
  # NBNB TODO remove plate_manipulater and treat as another sample changer
  - plate_manipulator: plate-manipulator-mockup.xml
  - diffractometer: diffractometer-mockup.xml
  - sample_view: sample-view.xml
  - lims: lims-client-mockup.xml
  - queue_manager: queue.xml
  - queue_model: queue-model.xml
  # Procedures:
  - collect: collect-mockup.xml
  - xrf_spectrum: xrf-spectrum-mockup.xml
  - energy_scan: energyscan-mockup.xml
  # - imaging: xray-imaging.xml # Only in EMBL as of 201907
  - gphl_connection: gphl-setup.yml
  - gphl_workflow: gphl-workflow.yml
  - xray_centring: xray_centring2.yml
  # - centring: centring.xml
  # Analysis:
  - offline_processing: offline-processing-mockup.xml
  - online_processing: online-processing-mockup.xml
  - characterisation: characterisation-mockup.xml
  # - beam_realign: # Skipped - optional

configuration:
  # Non-object attributes:
  advanced_methods:
    - MeshScan
    - XrayCentering

  tunable_wavelength: true
  disable_num_passes: false
  run_online_processing: false
  run_number: 1

  default_acquisition_parameters:
    default:
      # Default values, also used for standard acquisition.
      # Values not given in other dictionaries are taken from here
      exp_time: 0.04              # (s) exposure time
      osc_start: 0.0            # (degrees) Only used if no current angle found
      osc_range: 0.1              # (degrees)
      num_passes: 1               # (int)
      first_image: 1              # (int)
      overlap: 0
      num_images: 1               # (int)
      # detector_binning_mode: 1          # Removed as not in practice used.
      inverse_beam: false         # (bool)
      take_dark_current: true     # (bool)
      skip_existing_images: true  # (bool)
      take_snapshots: true        # (bool)

    helical:
      # Defaults for helical scan. Missing values are taken from default
      num_images: 100

    characterisation:
      # Defaults for chareacterisation. Missing values are taken from default
      osc_range: 1
      opt_sad: False  # yamllint disable-line rule:truthy
      account_rad_damage: True  # yamllint disable-line rule:truthy
      strategy_complexity: 0
      max_crystal_vdim: 1.0
      min_crystal_vdim: 1.0
      max_crystal_vphi: 1.0
      min_crystal_vphi: 1.0

    advanced:
      # Defaults for 'advanced' acquisition. Missing values are taken from default
      osc_range: 0.5
      num_images: 100

  acquisition_limit_values:
    exposure_time:     # (s)
      - 0.04
      - 6000.0
    osc_range:         # (degrees)
      - -1000.0
      - 10000.0
    number_of_images:  # (int)
      - 1
      - 99999
    kappa:             # (degrees)
      - 0.0
      - 180.0
#  kappa_phi:         # (degrees)
#    - 0.0
#    - 360.0
