# The class to initialise, and init parameters
_initialise_class:
    class: mxcubecore.HardwareObjects.Beamline.Beamline
    # Further key-value pairs here will be passed to the class init
#    mode: devel

# objects
#
# Eventually all objects should use the yaml config system like Beamline,
# but for now we can leave them as xml
#
# NBNB some objects that do not currently have their own config files
# would need those added (e.g. the centring methods)
#
_objects:
    # The !!o0map and the lines starting with '- ' give you an *orderd* dictionary
    # And thus a reproducible loading order
  !!omap
    # The values are the file paths to the configuration file for the
    # object, relative to the configuration file path(s)
    #
    # NB - the order is *NOT* arbitrary, as signal connnections are set
    # on one object that require the other to be already loaded.
    #
    # Hardware:
    - session: session.xml
    - machine_info: mach-info.xml
    - transmission: transmission.xml
    - energy: energy.xml
    #- beam_info: beam-info.xml
    - beam: beam.xml
    - flux: flux.xml
    - digital_zoom: digital-zoom.xml
    - sample_view: sample-view.xml
    - detector: pilatus.xml
    - resolution: resolution.xml
#    - hutch_interlock: door-interlock-mockup.xml
#    - safety_shutter: safety_shutter.xml
    - fast_shutter: fastshut.xml
    - sample_changer: cats.xml
    - sample_changer_maintenance: catsmaint.xml
    # NBNB TODO remove plate_manipulater and treat as another smaple changer
#    - plate_manipulator: plate-manipulator.xml
    - diffractometer: mini-diff.xml
    - lims: dbconnection.xml
    - queue_manager: queue.xml
    - queue_model: queue-model.xml
    # Procedures:
    - collect: mxcollect.xml
    #- xrf_spectrum: xrf-spectrum-mockup.xml
    #- energy_scan: energyscan.xml
    #    - imaging: xray-imaging.xml # Only in EMBL as of 201907
    - gphl_workflow: gphl-workflow.xml
    - gphl_connection: gphl-setup.xml
    - centring: centring-math.xml
    # Analysis:
    - image_tracking: image-tracking.xml
    - offline_processing: offline-processing.xml
    - online_processing: online-processing.xml
    - characterisation: characterisation.xml
    - xml_rpc_server: xml-rpc-server.xml
    # - beam_realign: # Skipped - optional
# Non-object attributes:
advanced_methods:
    - MeshScan
    - XrayCentering
tunable_wavelength: true
disable_num_passes: false
run_number: 1

default_acquisition_parameters:
    default:
        # Default values, also used for standard acquisition.
        # Values not given in other dictionaries are taken from here
        exp_time: 0.1               # (s) exposure time
        osc_start: 0.0              # (degrees) Only used if no current angle found
        osc_range: 0.1              # (degrees)
        num_passes: 1               # (int)
        first_image: 1              # (int)
        overlap: 0
        num_images: 1800               # (int)
        # detector_binning_mode: 1          # Removed as not in practice used.
        inverse_beam: false         # (bool)
        take_dark_current: true     # (bool)
        skip_existing_images: true  # (bool)
        take_snapshots: true        # (bool)
        kappa_phi: 0

    helical:
        # Defaults for helical scan. Missing values are taken from default
        exp_time: 0.08              # (s) exposure time

    characterisation:
        # Defaults for chareacterisation. Missing values are taken from default
        exp_time: 0.08               # (s) exposure time
        osc_range: 0.1

    mesh:
        # Defaults for 'advanced' acquisition. Missing values are taken from default
        exp_time: 0.08              # (s) exposure time
        osc_range: 0.0
        num_images: 100
        cell_counting: inverse-zig-zag
        cell_spacing: vertical,horizontal
        mesh_center: top-left

#    advanced:
#        # Defaults for 'advanced' acquisition. Missing values are taken from default
#        exp_time: 0.04              # (s) exposure time
#        osc_range: 0.5
#        num_images: 100

acquisition_limit_values:
    exposure_time:     # (s)
        - 0.08
        - 1000.0
    osc_range:         # (degrees)
        -  -2160.0
        -  2160.0
    number_of_images:  # (int)
        - 1
        - 9999
    kappa:             # (degrees)
        - -1.0
        - 180.0
    kappa_phi:         # (degrees)
        - -720.0
        - 720.0
