---

name: Linting & Code Quality

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install openldap
        # yamllint disable rule:line-length
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y libldap2-dev libsasl2-dev slapd ldap-utils tox lcov valgrind
        # yamllint enable rule:line-length

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry --user
          python -m poetry install

      - name: Run Pre-Commit
        run: |
          poetry run pre-commit run --all-files
